name: Go Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:

  TestMapReduce:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: ChangeDir
      run: cd src/raft
      
    - name: TestRaft
      run: bash ./go-test-many.sh 1000 4 2 -race
