name: Go Test

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:

  TestRaft:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - shell: bash
    - working-directory: src/raft
    - name: TestRaft
      run: bash ./go-test-many.sh 1000 4 2 -race
