name: Go Test

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:

  TestRaft:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: TestRaft
      run: ./go-test-many.sh 1000 4 2 -race
      shell: bash
      working-directory: src/raft
